name: Analysis Workflow

on:
  workflow_run:
    workflows: ["Testing Workflow"]
    types:
      - completed
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Download coverage artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-workflow.yml
          workflow_conclusion: success
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}