name: Server CI

on:
  push:
    branches: [main]
    paths: ['server/**']
  pull_request:
    branches: [main]
    paths: ['server/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server  # Critical for all commands

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Now works because we're in /server
      - run: npm ci
      - run: npm run test:ci