name: Full CI with SonarQube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'

      - name: Install server dependencies
        run: npm ci

      - name: Run server tests with coverage
        run: npm run test:ci

      - name: Verify server coverage file
        run: |
          ls -la coverage/
          [ -f coverage/lcov.info ] || exit 1
          echo "Server coverage file exists with $(wc -l < coverage/lcov.info) lines"
          
      - name: Save server coverage
        uses: actions/upload-artifact@v3
        with:
          name: server-coverage
          path: server/coverage/
          retention-days: 1

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install client dependencies
        run: npm ci

      - name: Install ts-node for Jest TypeScript config
        run: npm install --save-dev ts-node

      - name: Run client tests with coverage
        run: npm run test:coverage
        
      - name: Verify client coverage file
        run: |
          ls -la coverage/
          [ -f coverage/lcov.info ] || exit 1
          echo "Client coverage file exists with $(wc -l < coverage/lcov.info) lines"
          
      - name: Save client coverage
        uses: actions/upload-artifact@v3
        with:
          name: client-coverage
          path: client/coverage/
          retention-days: 1

  sonarcloud:
    needs: [test-server, test-client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download all coverage reports
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Prepare coverage reports for SonarQube
        run: |
          mkdir -p .coverage
          cp -r server-coverage/* .coverage/ || echo "No server coverage"
          cp -r client-coverage/* .coverage/ || echo "No client coverage"
          ls -la .coverage/

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}